### ISSUE TITLE
Unable to access the admin hub after > The POST method is not supported for route hub/login

### ISSUE THREAD

**Issue by iflow** [lunarphp/lunar#1147]
- Lunar version: 0.4.0
- Laravel Version: 10.15.0
- PHP Version: 8.1.2
- Database Driver & Version: MySQL

### Expected Behaviour:
You can access the admin hub at http://<yoursite>/hub

### Actual Behaviour:

1. A login form appears
2. After submitting the form with the username and password provided during installation the following error appears:
3. `The POST method is not supported for route hub/login. Supported methods: GET, HEAD.`

_Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException_

```
curl "http://localhost/lunar-shop/public/hub/login" \
   -X POST \
   -H 'host: localhost' \
```

### Steps To Reproduce:

1. Install Laravel
2. Install Lunar, see https://docs.lunarphp.io/core/installation.html
3. Try to access the admin hub

**Comment by glennjacobs** [comment]
You don't have your environment set up correctly. This is a classic Livewire problem, not Lunar related. Google and I'm sure you'll find the answer.

**Comment by pralhadstha** [comment]
For someone who is coming with the same problem. I found it in the alpha release.

First, check your console, and if you find this error:
_`GET https://localhost/livewire/livewire.js?id=07f22875 net::ERR_ABORTED 404 (Not Found)`_

The problem is due to your application URL. If you are using the **artisan server** the problem will go away.

But if you are not using the server then the solution would be to publish livewire assets using
**`php artisan livewire:publish --assets`**

Or if you have the livewire assets published under a different directory you could add the following codes to the **routes** and point to your custom path

```
use Livewire\Livewire;

Livewire::setScriptRoute(function ($handle) {
    return Route::get('/custom/public/vendor/livewires/livewire.js', $handle);
});
```
Official Docs link of the solution: 
https://livewire.laravel.com/docs/installation#customizing-the-asset-url

I hope someone will find this helpful.
