### ISSUE TITLE
Meilisearch package

### ISSUE THREAD

**Issue by glennjacobs** [lunarphp/lunar#1500]
Port existing Meilisearch package, making any improvements we feel necessary.

**Comment by lguichard** [comment]
@glennjacobs I already use Melisearch without external plugin, just install meilisearch/meilisearch-php.

What's do you need that features ? The oldest package doesn't include anything : https://github.com/lunarphp/meilisearch

**Comment by glennjacobs** [comment]
The idea is to set the Meilisearch index mappings based upon the attribute data configuration.

**Comment by omar-bfe** [comment]
Now the indexer is not calling [UpdateFiltrableAttributes](https://www.meilisearch.com/docs/learn/fine_tuning_results/filtering#configuring-filters) anywhere in the indexer logic. 
this is bug i have raised the issue here #1492
The Indexers logic is good i think it just needs some improvements. there is also an bug in indexing in fact when editing a product and only changing the media for example setting an other primary image or uploading a new image the change will not get reflected on the thumbnail in the search index cause this is just updating the Media Model and not the Product Model it needs a new hit on the save changes button so the Product Model get updated and so for the Search index

**Comment by lguichard** [comment]
@glennjacobs I make this PR soon.

**Comment by ryanmitchell** [comment]
This can be closed too as its been merged
