### ISSUE TITLE
Hub orders index throws ErrorException Attempt to read property "name" on null 

### ISSUE THREAD

**Issue by Rokasde** [lunarphp/lunar#302]
- GetCandy version: dev-main
- Laravel Version: 8.75
- PHP Version: 8.1
- Database Driver & Version: MySQL 8.0.28

### Expected Behaviour:
It should open orders list.

### Actual Behaviour:
ErrorException: Attempt to read property "name" on null.

### Steps To Reproduce:
By opening admin hub's orders list (hub/orders).

![image](https://user-images.githubusercontent.com/40316537/171105139-2594ebd6-bff1-42c5-9aae-1a4a05a4ea21.png)

**Comment by alecritson** [comment]
Hi @Rokasde Having a hard time reproducing this one, can you just confirm a few things:

1) Each order in the database has a `channel_id`
2) Which search driver are you using?
3) The exception references the `orders/index.blade.php` file, are you able to see if anything is being referenced in there from the stack trace?

It's confusing since the method shown above shouldn't actually be called when viewing the orders listing since it's used when indexing.

**Comment by Rokasde** [comment]
Hi @alecritson, 

1. Yes, all of the orders are assigned to default channel_id: 1.
2. Laravel scout mysql
3. I will dig deeper soon. 

It was a fresh demo-store install following the Quick Start guide in docs (https://docs.getcandy.io/quickstart.html). 
It should be quite easy to replicate the issue using the Quick Start guide and setting laravel scout to mysql driver.

**Comment by valdisd** [comment]
Also got this and came to search for it. 
But I installed this on the already created project.
laravel v8.83.15,
php 8.1
mysql 8.0
All tables are empty.
with scout driver as SCOUT_DRIVER=database.
If I change it to SCOUT_DRIVER=collection it works. 
Did not try with meilisearch for scout, as I'm still just testing.

Tell me if I can help, but I believe like Rokasde told. 
It should be quite easy to replicate the issue using the Quick Start guide and setting laravel scout to mysql driver.
