### ISSUE TITLE
multiple currencies and disabled

### ISSUE THREAD

**Issue by wychoong** [lunarphp/lunar#502]
- GetCandy version: 2.0-beta15

### Expected Behaviour:
when disable currency, it should be disabled and won't be required when filling product info

### Actual Behaviour:
validation fails when save product for disabled currency
![image](https://user-images.githubusercontent.com/67364036/187068302-45e2c9a4-0aea-4fbd-aa90-30e5931e49ad.png)

### Steps To Reproduce:
- more than 1 currency
- disable 1 currency
- fill prices except disabled currency

@glennjacobs mentioned on discord this could be:
1. on intention to avoid missing prices when re-enable the currency
2. for controlling currencies on frontend

for 1. i think it's valid but also at the same time the same issue will happen for adding new currency to the store. for 2., maybe a clearer label needed

**Comment by adam-code-labx** [comment]
@wychoong I think this one can be simply solved by just updating getCurrenciesProperty to check only if enabled
Looks like the hasPriceValidationRules depends on this, so I believe thats the only place that needs changing 👍 
I have way too many open PR's so will let you submit this one 😂

HasPrices.php line 205
```php
/**
 * Returns the currencies computed property.
 *
 * @return \Illuminate\Database\Eloquent\Collection
 */
public function getCurrenciesProperty()
{
    return Currency::whereEnabled(true)->get();
}
```

**Comment by wychoong** [comment]
@adam-code-labx yea, depends which behavior should be implemented

**Comment by adam-code-labx** [comment]
Well in terms of controlling currencies on the front-end. The livewire currencies property will not impact this.
So I see 2 different behaviour options for the hub based on one of more currencies disabled.

1. We exclude the disabled ones from the dropdown and do not allow to enter the price.
2. Include all currencies allow price to be filled but only validate enabled currency pricing.

I would suggest in the `getcandy-hub/system.php` config file an array for different behaviours then to set a default.
The developer can then choose the behaviour suited to their/client use case.

I plan to make similar suggestions for the addresses behaviour, however addresses will require to run migrations. 
Which could simply check the behaviour config and only run based on the required behaviour.

**Comment by wychoong** [comment]
> 2\. Include all currencies allow price to be filled but only validate enabled currency pricing.

I think this would be great. However this doesn’t address the initial intention for current behavior is to avoid missing prices when re-enable a currency. 

What I can think of now is to have a list to show products with missing prices, and only allow enabling currency when all products have the said currency’s price. And since new currency added is disabled by default, this could be good preventive measure for all scenarios can think of now

@glennjacobs what do you think?

**Comment by amitavroy** [comment]
Based on your solution, have raised a PR #1268 
It fixed this issue along with another issue that I faced in #1267

**Comment by glennjacobs** [comment]
Jumping in here as this topic is active again.

The original purpose for currencies being enabled or not was for storefront display. Perhaps a currency's exchange rate isn't so great and the store owner wants to stop offering it for the moment.

Regardless of whether a currency is enabled or not, we always want to capture the pricing information in the hub. Otherwise, if a currency is re-enabled we don't have the pricing data for the store.

So the issue comes, I think, when a store is initially installed and the developer wants a different currency, e.g. `EUR`, or when a store decides it no longer wants to offer a currency and never will going forward.

The first is fairly easy I guess, ensure all data that uses the currency is removed and then remove the currency.

The latter is more problematic, as we don't want to have to keep inputting prices, as we no longer want to support that currency, but we do have historic orders using it. Perhaps we should introduce soft deletes for this purpose?

We also have the same pricing data issue when a new currency is added. Perhaps #383 could assist with this to create initial prices for the new currency?

I also agree that the UI in the hub probably needs better descriptions to avoid confusion.

I would be interested in people's thoughts on this.

**Comment by wychoong** [comment]
a potential solution is to only validate enabled currency. When enabling a currency, it will check if all products are set with the currency, else it will not be able to enable. and a list of products with missing price will be displayed.

this way it:
- only validate enabled currency
- disable currency without soft delete
- can enable only if all products* with currency
- new currency added is disabled by default / or option to auto convert with exchange rate

if this is the way, we can then review the UI

**Comment by glennjacobs** [comment]
Right, so when creating a new currency it would have to be disabled by default (assuming we have products in the database). But the currency would still show in the hub when disabled (just not validated), so if we want to remove a currency completely we'd need a background task most likely.

**Comment by wychoong** [comment]
closing this issue as moving to 1.0 and no longer facing the original issue.
further handling of enable/disable currency as discussed here should be reviewed and open a new issue for v1.0
