### ISSUE TITLE
issues on Discount module

### ISSUE THREAD

**Issue by wychoong** [lunarphp/lunar#837]
for the discount module, i have a few questions:

- Lunar version: 0.2-rc1

issues:
1. max uses condition is not applied on calculation
2. where should `DiscountManager::validateCoupon` call from? only when add coupon to cart or during calculation too?
3. the BuyXGetY type doesn't consider Conditions(coupon/,min cart) when applying discount?
4. bug in applying discount on product limitation https://github.com/lunarphp/lunar/pull/813#discussion_r1092141267
5. min spend condition for discount doesn't convert with currency factor https://github.com/lunarphp/lunar/blob/32739b8c91cc1c4f072ab10baa25d7cec5d6fe74/packages/core/src/DiscountTypes/Discount.php#L36
6. discount amount doesn't convert with currency factor https://github.com/lunarphp/lunar/blob/32739b8c91cc1c4f072ab10baa25d7cec5d6fe74/packages/core/src/DiscountTypes/Discount.php#L68

**Comment by wychoong** [comment]
4. is confirmed by ryan

**Comment by alecritson** [comment]
@wychoong Are these points now resolved from the recent PR's? Just trying to go through issues for discounts specifically to see what's outstanding.

**Comment by wychoong** [comment]
> @wychoong Are these points now resolved from the recent PR's? Just trying to go through issues for discounts specifically to see what's outstanding.

1,4,5,6 are resolved.

2 & 3 requires core team's clarification to determine require fix or not

**Comment by alecritson** [comment]
2) `DiscountManager::validateCoupon` is a helper for storefronts to check whether the coupon should add to the cart, I've started a validation rule class too so you will be able to easily add it to the usual Laravel validation rules.

The individual discount types will handle if the logic applies.

3) I think it's correct if the BuyXGetY checks the coupon since it's a cart level column, I assume we should be able to use the extracted logic from your previous PR 🤔

**Comment by wychoong** [comment]
thanks, this clarifies. will close it for now.
